name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create Release ZIP
        run: |
          mkdir -p release
          zip -r release/wp-content-helper.zip . \
            -x "*.git*" \
            -x "*node_modules/*" \
            -x "*vendor/*" \
            -x "*.DS_Store" \
            -x "release/*"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/wp-content-helper.zip
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
